id: build-fix
name: 빌드 에러 수정
version: "1.0"
description: |
  TypeScript, 빌드, 린트 에러를 최소한의 변경으로 수정합니다.
  아키텍처 변경 없이 빌드를 그린으로 만드는 것에 집중합니다.
use_cases:
  - TypeScript 컴파일 에러 수정
  - 빌드 실패 복구
  - 린트 에러 자동 수정
triggers:
  error_patterns:
    - "error TS"
    - "SyntaxError"
    - "Cannot find module"
    - "Type .* is not assignable"
    - "npm ERR!"
    - "build failed"
  keywords:
    high: [빌드 에러, 타입 에러, 컴파일 실패, build failed, type error]
    medium: [에러 수정, fix error]
    low: [빨간줄, 에러]
capabilities: [typescript_fix, build_fix, lint_fix]
outputs:
  - type: fix_report
    format: markdown
prompt_template: |
  빌드 에러가 발생했습니다. 최소한의 변경으로 수정하세요.
  아키텍처를 변경하지 마세요. 빌드를 그린으로 만드는 것에 집중하세요.
context:
  agents:
    - build-fixer
    - build-fixer-low
    - ultraplan-executor
    - executor
    - executor-high
    - gsd-debugger
  phases: [execution]
  trigger_events: [on_build_error]
model_routing:
  default: sonnet
synergies: [tdd, tdd-guide, security-review, code-review]
