id: security-review
name: 보안 리뷰
version: "1.0"
description: |
  OWASP Top 10 기준 보안 검사. 시크릿 누출, XSS, CSRF, 인젝션 탐지.
use_cases:
  - 보안 취약점 분석
  - 시크릿/크레덴셜 검사
  - OWASP Top 10 검증
triggers:
  error_patterns: [XSS, CSRF, "SQL injection", secret, credential]
  keywords:
    high: [보안 리뷰, security review, 취약점, vulnerability, OWASP]
    medium: [보안 검사, 시크릿 검사]
    low: [보안, security]
capabilities: [security_audit, vulnerability_scan, secret_detection]
outputs:
  - type: security_report
    format: markdown
prompt_template: |
  OWASP Top 10 기준으로 보안 리뷰를 수행하세요.
  하드코딩된 시크릿, XSS, CSRF, 인젝션을 중점 확인하세요.
context:
  agents:
    - security-reviewer
    - security-reviewer-low
    - ultraplan-architect
    - ultraplan-critic
    - code-analyzer
  phases: [verification, review]
  trigger_events: [on_execution_complete]
model_routing:
  default: opus
synergies: [code-review, phase-7-seo-security]
