id: tdd-guide
name: TDD 가이드
version: "1.0"
description: |
  테스트 주도 개발 가이드. Red-Green-Refactor 사이클 강제.
use_cases:
  - TDD로 기능 개발
  - 테스트 커버리지 확보
triggers:
  keywords:
    high: [TDD, 테스트 먼저, test first, 테스트 주도]
    medium: [테스트 작성, 유닛 테스트, unit test]
    low: [테스트]
capabilities: [test_first_development, red_green_refactor]
outputs:
  - type: test_plan
    format: markdown
prompt_template: |
  TDD를 적용하세요.
  1. RED: 실패하는 테스트 먼저 작성
  2. GREEN: 테스트 통과하는 최소 구현
  3. REFACTOR: 코드 정리
context:
  agents:
    - tdd-guide
    - tdd-guide-low
    - ultraplan-executor
    - executor
    - executor-high
    - qa-tester
    - qa-tester-high
  phases: [execution, testing]
  trigger_events: [on_tdd_mode]
model_routing:
  default: sonnet
synergies: [build-fix, code-review, ultraqa]
