id: vision-analysis
name: 이미지 분석
version: "1.0"
description: |
  이미지, 스크린샷, 다이어그램, 목업을 분석하여 UI 요소를 추출합니다.
use_cases:
  - 스크린샷 분석
  - 목업/디자인 파일 해석
  - 다이어그램 분석
triggers:
  input_types: [image, screenshot, mockup, diagram]
  keywords:
    high: [이미지 분석, 스크린샷 분석, vision analysis, 목업 분석]
    medium: [이미지, 스크린샷, 분석]
    low: [사진, 그림]
capabilities: [image_analysis, ui_extraction, diagram_parsing]
outputs:
  - type: analysis_report
    format: markdown
prompt_template: |
  이미지를 분석하여 UI 요소, 레이아웃, 색상, 타이포그래피를 추출하세요.
context:
  agents:
    - vision
    - designer
    - designer-high
    - design-validator
    - ultraplan-executor
  phases: [design, research]
  trigger_events: [on_image_input]
model_routing:
  default: opus
synergies: [design-audit, frontend-ui-ux, component-builder]
